server:
  port: 0
spring:
  application:
    name: KeycloakResourceServer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/keycloak-oauth2/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}